### PR TITLE
Bump version to 2023.3

### PR DESCRIPTION
**Pull request by joedevivo**
Specifically effects RustRover EAP

### CODE REVIEW

**Comment by fehnomenal** [comment]
Thank you!

**Comment by netthier** [comment]
I'd also appreciate this being merged.

**Comment by joedevivo** [comment]
I've been using a locally compiled version for a while now. Would love to see this merged as well.

For what it's worth, this also came from wanting to use rust rover with nix, and if you're in a nix dev shell, `rustrover .` will pick up the environment that direnv did in the shell.

**Comment by joedevivo** [comment]
For anyone that wants it, you can download this build and use it directly. [Direnv integration-0.2.8.zip](https://github.com/fehnomenal/intellij-direnv/files/13503769/Direnv.integration-0.2.8.zip)

**Comment by viperML** [comment]
I've tried with RustRover and seems to work OK

**Comment by phip1611** [comment]
@fehnomenal any update? :)

**Comment by huyz** [comment]
Why not just bump it to `299.*` so we don't have to keep doing this?  It's fine if eventually it breaks. Better than having it stop working on every upgrade.

**Comment by huyz** [comment]
Btw, the easiest workaround for all is to clone the repo locally, fix the `pluginUntilBuild`, build, and `Install Plugin from Disk…`

**Pull request closed without merging**
